version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - Splatterxl
  ignore:
  - dependency-name: discord-slash-commands-client
    versions:
    - "> 1.1.0"
    - "< 2"
